#cloud-config
package_update: true
package_upgrade: true
packages:
  - wireguard
  - wireguard-tools
runcmd:
  - echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
  - sysctl --system
  - systemctl enable --now wg-quick@wg0
