#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
write_files:
  - encoding: b64
    content: ${frps_ini}
    owner: root:root
    path: /etc/frp/frps.ini
    permissions: "0644"
runcmd:
  - docker run -d -it --restart always ${ports} -v /etc/frp:/etc/frp ${frps_image} -c /etc/frp/frps.ini
  - reboot
