- hosts: servers, clients
  remote_user: root
  tasks:
    - name: Update system
      shell: |
        apt update
        apt -y upgrade
    - name: Reboot
      ansible.builtin.reboot:
        reboot_timeout: 3600
